### ISSUE TITLE
Problem of setLabelCol

### ISSUE THREAD

**Issue by clussificate** [titicaca/spark-gbtlr#2]
It seems that the name of  LableCol must be "label". 
If I use other name, such as "y", there is a Exception " java.lang.IllegalArgumentException:  Field "label" does not exist." 
SO, I try to add .setLabelCol($(labelCol)) in logisticRegression
the problem was resolved!

**Comment by titicaca** [comment]
Pull request is merged! Thank you once again for reporting the issue.
